<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MRS.InstallationOptions\MRS.InstallationOptions.csproj" />
    <ProjectReference Include="..\MRS.DismEngine\MRS.DismEngine.csproj" />
    <ProjectReference Include="..\MRS.ImageEngine\MRS.ImageEngine.csproj" />
  </ItemGroup>

</Project>
